services:
  master:
    hostname: master
    build: master/
    ports:
      - "8080:8080"
    networks:
      - cluster-network

  secondary-1:
    hostname: secondary-1
    build: secondary/
    ports:
      - "8081:8081"
    networks:
      - cluster-network

  secondary-2:
    hostname: secondary-2
    build: secondary/
    ports:
      - "8082:8081"
    networks:
      - cluster-network

networks:
  cluster-network: